<?php

namespace Database\Seeders;


use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SalesLotSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sales_lots')->insert([
            [
                'product_id' => 1,
                'description' => 'Autumn Harvest',
                'price' => 5,
                'initial_quantity' => 30,
                'current_quantity' => 30,
                'discount' => 10,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 3,
                'description' => 'Garden Galore',
                'price' => 40,
                'initial_quantity' => 22,
                'current_quantity' => 22,
                'discount' => 5,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 5,
                'description' => 'Happy Day Sale',
                'price' => 39,
                'initial_quantity' => 11,
                'current_quantity' => 11,
                'discount' => 20,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 7,
                'description' => 'Autumn Harvest',
                'price' => 17,
                'initial_quantity' => 32,
                'current_quantity' => 32,
                'discount' => 15,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 9,
                'description' => 'Happy Day Sale',
                'price' => 5,
                'initial_quantity' => 49,
                'current_quantity' => 49,
                'discount' => 15,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 11,
                'description' => 'Eco-Friendly Awareness',
                'price' => 16,
                'initial_quantity' => 20,
                'current_quantity' => 20,
                'discount' => 16,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 13,
                'description' => 'Winter Clearance',
                'price' => 22,
                'initial_quantity' => 17,
                'current_quantity' => 17,
                'discount' => 7,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 15,
                'description' => 'Summer Fiesta',
                'price' => 29,
                'initial_quantity' => 32,
                'current_quantity' => 32,
                'discount' => 8,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 17,
                'description' => 'Tech Tuesday',
                'price' => 27,
                'initial_quantity' => 11,
                'current_quantity' => 11,
                'discount' => 20,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 19,
                'description' => 'Spring Special',
                'price' => 40,
                'initial_quantity' => 46,
                'current_quantity' => 46,
                'discount' => 17,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 21,
                'description' => 'Fashion Forward',
                'price' => 10,
                'initial_quantity' => 43,
                'current_quantity' => 43,
                'discount' => 12,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 23,
                'description' => 'Happy Day Sale',
                'price' => 15,
                'initial_quantity' => 23,
                'current_quantity' => 23,
                'discount' => 5,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 25,
                'description' => 'Book Lovers Day',
                'price' => 37,
                'initial_quantity' => 41,
                'current_quantity' => 41,
                'discount' => 5,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 27,
                'description' => 'Autumn Harvest',
                'price' => 38,
                'initial_quantity' => 23,
                'current_quantity' => 23,
                'discount' => 14,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 29,
                'description' => 'Fitness Frenzy',
                'price' => 19,
                'initial_quantity' => 24,
                'current_quantity' => 24,
                'discount' => 16,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 31,
                'description' => 'Fashion Forward',
                'price' => 29,
                'initial_quantity' => 25,
                'current_quantity' => 25,
                'discount' => 15,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 33,
                'description' => 'Book Lovers Day',
                'price' => 19,
                'initial_quantity' => 36,
                'current_quantity' => 36,
                'discount' => 11,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 35,
                'description' => 'Tech Tuesday',
                'price' => 34,
                'initial_quantity' => 44,
                'current_quantity' => 44,
                'discount' => 11,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 37,
                'description' => 'Spring Special',
                'price' => 32,
                'initial_quantity' => 50,
                'current_quantity' => 50,
                'discount' => 6,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 39,
                'description' => 'Pet Care Week',
                'price' => 18,
                'initial_quantity' => 6,
                'current_quantity' => 6,
                'discount' => 14,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 41,
                'description' => 'Summer Fiesta',
                'price' => 5,
                'initial_quantity' => 48,
                'current_quantity' => 48,
                'discount' => 11,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 43,
                'description' => 'Spring Special',
                'price' => 15,
                'initial_quantity' => 39,
                'current_quantity' => 39,
                'discount' => 14,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 45,
                'description' => 'Summer Fiesta',
                'price' => 20,
                'initial_quantity' => 35,
                'current_quantity' => 35,
                'discount' => 16,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 47,
                'description' => 'Spring Special',
                'price' => 28,
                'initial_quantity' => 41,
                'current_quantity' => 41,
                'discount' => 11,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 49,
                'description' => 'Weekend Bonanza',
                'price' => 9,
                'initial_quantity' => 44,
                'current_quantity' => 44,
                'discount' => 12,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 51,
                'description' => 'Fitness Frenzy',
                'price' => 26,
                'initial_quantity' => 45,
                'current_quantity' => 45,
                'discount' => 19,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 53,
                'description' => 'Tech Tuesday',
                'price' => 15,
                'initial_quantity' => 12,
                'current_quantity' => 12,
                'discount' => 20,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 55,
                'description' => 'Fitness Frenzy',
                'price' => 40,
                'initial_quantity' => 15,
                'current_quantity' => 15,
                'discount' => 14,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 57,
                'description' => 'Pet Care Week',
                'price' => 15,
                'initial_quantity' => 29,
                'current_quantity' => 29,
                'discount' => 12,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 59,
                'description' => 'Pet Care Week',
                'price' => 14,
                'initial_quantity' => 41,
                'current_quantity' => 41,
                'discount' => 16,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 61,
                'description' => 'Eco-Friendly Awareness',
                'price' => 27,
                'initial_quantity' => 19,
                'current_quantity' => 19,
                'discount' => 8,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 63,
                'description' => 'Autumn Harvest',
                'price' => 26,
                'initial_quantity' => 20,
                'current_quantity' => 20,
                'discount' => 20,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 65,
                'description' => 'Winter Clearance',
                'price' => 5,
                'initial_quantity' => 32,
                'current_quantity' => 32,
                'discount' => 13,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 67,
                'description' => 'Tech Tuesday',
                'price' => 7,
                'initial_quantity' => 10,
                'current_quantity' => 10,
                'discount' => 16,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 69,
                'description' => 'Food Waste Reduction Day',
                'price' => 18,
                'initial_quantity' => 9,
                'current_quantity' => 9,
                'discount' => 13,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 71,
                'description' => 'Summer Fiesta',
                'price' => 24,
                'initial_quantity' => 50,
                'current_quantity' => 50,
                'discount' => 5,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 73,
                'description' => 'Weekend Bonanza',
                'price' => 27,
                'initial_quantity' => 12,
                'current_quantity' => 12,
                'discount' => 13,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 75,
                'description' => 'Spring Special',
                'price' => 11,
                'initial_quantity' => 23,
                'current_quantity' => 23,
                'discount' => 14,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 77,
                'description' => 'Book Lovers Day',
                'price' => 14,
                'initial_quantity' => 49,
                'current_quantity' => 49,
                'discount' => 18,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 79,
                'description' => 'Weekend Bonanza',
                'price' => 26,
                'initial_quantity' => 37,
                'current_quantity' => 37,
                'discount' => 12,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 81,
                'description' => 'Autumn Harvest',
                'price' => 38,
                'initial_quantity' => 41,
                'current_quantity' => 41,
                'discount' => 5,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 83,
                'description' => 'Winter Clearance',
                'price' => 40,
                'initial_quantity' => 49,
                'current_quantity' => 49,
                'discount' => 8,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 85,
                'description' => 'Eco-Friendly Awareness',
                'price' => 32,
                'initial_quantity' => 42,
                'current_quantity' => 42,
                'discount' => 8,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 87,
                'description' => 'Happy Day Sale',
                'price' => 26,
                'initial_quantity' => 13,
                'current_quantity' => 13,
                'discount' => 17,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 89,
                'description' => 'Back to School',
                'price' => 9,
                'initial_quantity' => 35,
                'current_quantity' => 35,
                'discount' => 12,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 91,
                'description' => 'Eco-Friendly Awareness',
                'price' => 38,
                'initial_quantity' => 24,
                'current_quantity' => 24,
                'discount' => 11,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 93,
                'description' => 'Happy Day Sale',
                'price' => 32,
                'initial_quantity' => 39,
                'current_quantity' => 39,
                'discount' => 17,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 95,
                'description' => 'Back to School',
                'price' => 36,
                'initial_quantity' => 30,
                'current_quantity' => 30,
                'discount' => 17,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 97,
                'description' => 'Book Lovers Day',
                'price' => 39,
                'initial_quantity' => 45,
                'current_quantity' => 45,
                'discount' => 16,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                'product_id' => 99,
                'description' => 'Winter Clearance',
                'price' => 35,
                'initial_quantity' => 42,
                'current_quantity' => 42,
                'discount' => 12,
                'start_date' => now(),
                'end_date' => now()->addHours(5),
            ],
            [
                "product_id" => 101,
                "description" => "David's Deal",
                "price" => 15,
                "initial_quantity" => 10,
                "current_quantity" => 10,
                "discount" => 30,
                "start_date" => now(),
                "end_date" => now()->addHours(5),
            ]
        ]);
    }
}
