<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert(
            [
                [
                    'firstname' => 'Riccardo',
                    'lastname' => 'lastCall',
                    'email' => 'ric@lastcall.lu',
                    'password' => Hash::make('password'),
                    'phonenumber' => '3333333333',
                    'role' => 'admin',
                    'profileImg' => 'profileImages/1.png',
                ],
                [
                    'firstname' => 'Luiza',
                    'lastname' => 'lastCall',
                    'email' => 'lu@lastcall.lu',
                    'password' => Hash::make('password'),
                    'phonenumber' => '3333333333',
                    'role' => 'admin',
                    'profileImg' => 'profileImages/2.png',
                ],
                [
                    'firstname' => 'Brandon',
                    'lastname' => 'lastCall',
                    'email' => 'bran@lastcall.lu',
                    'password' => Hash::make('password'),
                    'phonenumber' => '3333333333',
                    'role' => 'admin',
                    'profileImg' => 'profileImages/3.png',
                ],
                [
                    'firstname' => 'Antoine',
                    'lastname' => 'lastCall',
                    'email' => 'ant@lastcall.lu',
                    'password' => Hash::make('password'),
                    'phonenumber' => '3333333333',
                    'role' => 'admin',
                    'profileImg' => 'profileImages/4.png',
                ],
                [
                    'firstname' => 'Dany',
                    'lastname' => 'lastCall',
                    'email' => 'dan@lastcall.lu',
                    'password' => Hash::make('password'),
                    'phonenumber' => '3333333333',
                    'role' => 'admin',
                    'profileImg' => 'profileImages/5.png',
                ],
                [
                    'firstname' => 'Alice',
                    'lastname' => 'Johnson',
                    'email' => 'alice.johnson@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '1112223333',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/6.png',
                ],
                [
                    'firstname' => 'Bob',
                    'lastname' => 'Smith',
                    'email' => 'bob.smith@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '2223334444',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/7.png',
                ],
                [
                    'firstname' => 'Charlie',
                    'lastname' => 'Wilson',
                    'email' => 'charlie.wilson@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '3334445555',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/8.png',
                ],
                [
                    'firstname' => 'David',
                    'lastname' => 'Brown',
                    'email' => 'david.brown@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '4445556666',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/9.png',
                ],
                [
                    'firstname' => 'Angela',
                    'lastname' => 'Davis',
                    'email' => 'angela.davis@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '5556667777',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/10.png',
                ],
                [
                    'firstname' => 'Frank',
                    'lastname' => 'Miller',
                    'email' => 'frank.miller@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '6667778888',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/11.png',
                ],
                [
                    'firstname' => 'Grace',
                    'lastname' => 'Lee',
                    'email' => 'grace.lee@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '7778889999',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/12.png',
                ],
                [
                    'firstname' => 'Hannah',
                    'lastname' => 'Martin',
                    'email' => 'hannah.martin@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '8889990000',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/13.png',
                ],
                [
                    'firstname' => 'Isaac',
                    'lastname' => 'Thompson',
                    'email' => 'isaac.thompson@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '9990001111',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/14.png',
                ],
                [
                    'firstname' => 'Jack',
                    'lastname' => 'Anderson',
                    'email' => 'jack.anderson@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '0001112222',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/15.png',
                ],
                [
                    'firstname' => 'Katherine',
                    'lastname' => 'White',
                    'email' => 'katherine.white@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '1112223333',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/16.png',
                ],
                [
                    'firstname' => 'Liam',
                    'lastname' => 'Jackson',
                    'email' => 'liam.jackson@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '2223334444',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/17.png',
                ],
                [
                    'firstname' => 'Mia',
                    'lastname' => 'Garcia',
                    'email' => 'mia.garcia@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '3334445555',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/18.png',
                ],
                [
                    'firstname' => 'Noah',
                    'lastname' => 'Hernandez',
                    'email' => 'noah.hernandez@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '4445556666',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/19.png',
                ],
                [
                    'firstname' => 'Olivia',
                    'lastname' => 'Lopez',
                    'email' => 'olivia.lopez@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '5556667777',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/20.png',
                ],
                [
                    'firstname' => 'Patrick',
                    'lastname' => 'Young',
                    'email' => 'patrick.young@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '6667778888',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/21.png',
                ],
                [
                    'firstname' => 'Quinn',
                    'lastname' => 'Perez',
                    'email' => 'quinn.perez@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '7778889999',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/22.png',
                ],
                [
                    'firstname' => 'Ryan',
                    'lastname' => 'Hall',
                    'email' => 'ryan.hall@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '8889990000',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/23.png',
                ],
                [
                    'firstname' => 'Sophia',
                    'lastname' => 'Martinez',
                    'email' => 'sophia.martinez@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '9990001111',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/24.png',
                ],
                [
                    'firstname' => 'Mario',
                    'lastname' => 'Bros',
                    'email' => 'mario.bros@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '9990001111',
                    'role' => 'restaurantManager',
                    'profileImg' => 'profileImages/25.png',
                ],
                [
                    'firstname' => 'John',
                    'lastname' => 'Doe',
                    'email' => 'john.doe@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '1112223333',
                    'role' => 'user',
                    'profileImg' => 'profileImages/26.png',
                ],
                [
                    'firstname' => 'Jane',
                    'lastname' => 'Smith',
                    'email' => 'jane.smith@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '2223334444',
                    'role' => 'user',
                    'profileImg' => 'profileImages/27.png',
                ],
                [
                    'firstname' => 'Michael',
                    'lastname' => 'Johnson',
                    'email' => 'michael.johnson@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '3334445555',
                    'role' => 'user',
                    'profileImg' => 'profileImages/28.png',
                ],
                [
                    'firstname' => 'Emily',
                    'lastname' => 'Davis',
                    'email' => 'emily.davis@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '4445556666',
                    'role' => 'user',
                    'profileImg' => 'profileImages/29.png',
                ],
                [
                    'firstname' => 'William',
                    'lastname' => 'Brown',
                    'email' => 'william.brown@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '5556667777',
                    'role' => 'user',
                    'profileImg' => 'profileImages/30.png',
                ],
                [
                    'firstname' => 'Olivia',
                    'lastname' => 'Miller',
                    'email' => 'olivia.miller@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '6667778888',
                    'role' => 'user',
                    'profileImg' => 'profileImages/31.png',
                ],
                [
                    'firstname' => 'Sophia',
                    'lastname' => 'Williams',
                    'email' => 'sophia.williams@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '7778889999',
                    'role' => 'user',
                    'profileImg' => 'profileImages/32.png',
                ],
                [
                    'firstname' => 'James',
                    'lastname' => 'Martin',
                    'email' => 'james.martin@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '8889990000',
                    'role' => 'user',
                    'profileImg' => 'profileImages/33.png',
                ],
                [
                    'firstname' => 'Isabella',
                    'lastname' => 'Thompson',
                    'email' => 'isabella.thompson@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '9990001111',
                    'role' => 'user',
                    'profileImg' => 'profileImages/34.png',
                ],
                [
                    'firstname' => 'Daniel',
                    'lastname' => 'Wilson',
                    'email' => 'daniel.wilson@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '0001112222',
                    'role' => 'user',
                    'profileImg' => 'profileImages/35.png',
                ],
                [
                    'firstname' => 'Ava',
                    'lastname' => 'White',
                    'email' => 'ava.white@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '1112223333',
                    'role' => 'user',
                    'profileImg' => 'profileImages/36.png',
                ],
                [
                    'firstname' => 'Mia',
                    'lastname' => 'Jackson',
                    'email' => 'mia.jackson@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '2223334444',
                    'role' => 'user',
                    'profileImg' => 'profileImages/37.png',
                ],
                [
                    'firstname' => 'Noah',
                    'lastname' => 'Garcia',
                    'email' => 'noah.garcia@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '3334445555',
                    'role' => 'user',
                    'profileImg' => 'profileImages/38.png',
                ],
                [
                    'firstname' => 'Liam',
                    'lastname' => 'Hernandez',
                    'email' => 'liam.hernandez@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '4445556666',
                    'role' => 'user',
                    'profileImg' => 'profileImages/39.png',
                ],
                [
                    'firstname' => 'Ella',
                    'lastname' => 'Lopez',
                    'email' => 'ella.lopez@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '5556667777',
                    'role' => 'user',
                    'profileImg' => 'profileImages/40.png',
                ],
                [
                    'firstname' => 'Ethan',
                    'lastname' => 'Young',
                    'email' => 'ethan.young@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '6667778888',
                    'role' => 'user',
                    'profileImg' => 'profileImages/41.png',
                ],
                [
                    'firstname' => 'Avery',
                    'lastname' => 'Perez',
                    'email' => 'avery.perez@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '7778889999',
                    'role' => 'user',
                    'profileImg' => 'profileImages/42.png',
                ],
                [
                    'firstname' => 'Charlotte',
                    'lastname' => 'Hall',
                    'email' => 'charlotte.hall@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '8889990000',
                    'role' => 'user',
                    'profileImg' => 'profileImages/43.png',
                ],
                [
                    'firstname' => 'Jackson',
                    'lastname' => 'Martinez',
                    'email' => 'jackson.martinez@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '9990001111',
                    'role' => 'user',
                    'profileImg' => 'profileImages/44.png',
                ],
                [
                    'firstname' => 'Marielle',
                    'lastname' => 'Martinez',
                    'email' => 'marielle.martinez@example.com',
                    'password' => Hash::make('password'),
                    'phonenumber' => '9990001111',
                    'role' => 'user',
                    'profileImg' => 'profileImages/45.png',
                ],
            ]

        );
    }
}
